version: 2
jobs:
  build:
    docker:
      - image: circleci/php:5.6-node-browsers
    working_directory: ~/laravel
    steps:
      - checkout

      - run:
          name: Update Composer to Latest Version
          command: composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run:
          name: Composer Install
          command: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      - run:
          name: Test 1 - Code Sniffer
          command: composer gscs
